# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-21 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('city_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('num_issues', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('rep_location', models.CharField(max_length=100)),
                ('num_issues', models.IntegerField(default=0)),
                ('bio', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discussions.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.Politician'),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discussions.AppUser'),
        ),
    ]
