# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_issue_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.AppUser'),
        ),
    ]
